# Generated by Django 2.1.4 on 2018-12-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('buy_date', models.DateTimeField()),
                ('condition', models.CharField(choices=[('bad', 'bad'), ('ok', 'ok'), ('new', 'new')], max_length=200)),
            ],
        ),
    ]
